/* eslint-disable object-curly-newline */
module.exports = {
  FeatureName: 'Acrobat Online Edit',
  features: [
    {
      tcid: '0',
      name: '@online-pdf-editor-smoke',
      path: '/acrobat/online/pdf-editor',
      verb: 'add-comment',
      data: {},
      tags: '@online @edit @verbs @pdf-editor @smoke @live',
    },
    {
      tcid: '1',
      name: '@online-merge-pdf-smoke',
      path: '/acrobat/online/merge-pdf',
      verb: 'combine-pdf',
      data: {},
      tags: '@online @edit @verbs @merge-pdf @smoke @live',
    },
    {
      tcid: '2',
      name: '@online-split-pdf-smoke',
      path: '/acrobat/online/split-pdf',
      verb: 'split-pdf',
      data: {},
      tags: '@online @edit @verbs @split-pdf @smoke @live',
    },
    {
      tcid: '3',
      name: '@online-crop-pdf-smoke',
      path: '/acrobat/online/crop-pdf',
      verb: 'crop-pages',
      data: {},
      tags: '@online @edit @verbs @crop-pdf @smoke @live',
    },
    {
      tcid: '4',
      name: '@online-delete-pdf-pages-smoke',
      path: '/acrobat/online/delete-pdf-pages',
      verb: 'delete-pages',
      data: {},
      tags: '@online @edit @verbs @delete-pdf-pages @smoke @live',
    },
    {
      tcid: '5',
      name: '@online-rotate-pdf-smoke',
      path: '/acrobat/online/rotate-pdf',
      verb: 'rotate-pages',
      data: {},
      tags: '@online @edit @verbs @rotate-pdf @smoke @live',
    },
    {
      tcid: '6',
      name: '@online-rearrange-pdf-smoke',
      path: '/acrobat/online/rearrange-pdf',
      verb: 'reorder-pages',
      data: {},
      tags: '@online @edit @verbs @rearrange-pdf @smoke @live',
    },
    {
      tcid: '7',
      name: '@online-extract-pdf-pages-smoke',
      path: '/acrobat/online/extract-pdf-pages',
      verb: 'extract-pages',
      data: {},
      tags: '@online @edit @verbs @extract-pdf-pages @smoke @live',
    },
    {
      tcid: '8',
      name: '@online-add-pages-to-pdf-smoke',
      path: '/acrobat/online/add-pages-to-pdf',
      verb: 'insert-pdf',
      data: {},
      tags: '@online @edit @verbs @add-pages-to-pdf @smoke @live',
    },
    {
      tcid: '9',
      name: '@online-add-pdf-page-numbers-smoke',
      path: '/acrobat/online/add-pdf-page-numbers',
      verb: 'number-pages',
      data: {},
      tags: '@online @edit @verbs @add-pdf-page-numbers @smoke @live',
    },
  ],
};
