/* eslint-disable object-curly-newline */
module.exports = {
  FeatureName: 'Acrobat Online Convert',
  features: [
    {
      tcid: '0',
      name: '@online-pdf-to-word-smoke',
      path: '/acrobat/online/pdf-to-word',
      verb: 'pdf-to-word',
      data: {},
      tags: '@online @convert @verbs @pdf-to-word @smoke @live',
    },
    {
      tcid: '1',
      name: '@online-pdf-to-excel-smoke',
      path: '/acrobat/online/pdf-to-excel',
      verb: 'pdf-to-excel',
      data: {},
      tags: '@online @convert @verbs @pdf-to-excel @smoke @live',
    },
    {
      tcid: '2',
      name: '@online-pdf-to-ppt-smoke',
      path: '/acrobat/online/pdf-to-ppt',
      verb: 'pdf-to-ppt',
      data: {},
      tags: '@online @convert @verbs @pdf-to-ppt @smoke @live',
    },
    {
      tcid: '3',
      name: '@online-pdf-to-jpg-smoke',
      path: '/acrobat/online/pdf-to-jpg',
      verb: 'pdf-to-image',
      data: {},
      tags: '@online @convert @verbs @pdf-to-jpg @smoke @live',
    },
    {
      tcid: '4',
      name: '@online-pdf-to-png-smoke',
      path: '/acrobat/online/pdf-to-png',
      verb: 'pdf-to-png',
      data: {},
      tags: '@online @convert @verbs @pdf-to-png @smoke @live',
    },
    {
      tcid: '5',
      name: '@online-word-to-pdf-smoke',
      path: '/acrobat/online/word-to-pdf',
      verb: 'word-to-pdf',
      data: {},
      tags: '@online @convert @verbs @word-to-pdf @smoke @live',
    },
    {
      tcid: '6',
      name: '@online-excel-to-pdf-smoke',
      path: '/acrobat/online/excel-to-pdf',
      verb: 'excel-to-pdf',
      data: {},
      tags: '@online @convert @verbs @excel-to-pdf @smoke @live',
    },
    {
      tcid: '7',
      name: '@online-ppt-to-pdf-smoke',
      path: '/acrobat/online/ppt-to-pdf',
      verb: 'ppt-to-pdf',
      data: {},
      tags: '@online @convert @verbs @ppt-to-pdf @smoke @live',
    },
    {
      tcid: '8',
      name: '@online-jpg-to-pdf-smoke',
      path: '/acrobat/online/jpg-to-pdf',
      verb: 'jpg-to-pdf',
      data: {},
      tags: '@online @convert @verbs @jpg-to-pdf @smoke @live',
    },
    {
      tcid: '9',
      name: '@online-png-to-pdf-smoke',
      path: '/acrobat/online/png-to-pdf',
      verb: 'png-to-pdf',
      data: {},
      tags: '@online @convert @verbs @png-to-pdf @smoke @live',
    },
    {
      tcid: '10',
      name: '@online-heic-to-pdf-smoke',
      path: 'https://acrobat.adobe.com/heic-to-pdf',
      verb: 'heic-to-pdf',
      data: {},
      tags: '@online @convert @verbs @heic-to-pdf @smoke @live',
    },
    {
      tcid: '11',
      name: '@online-convert-pdf-smoke',
      path: '/acrobat/online/convert-pdf',
      verb: 'createpdf',
      data: {},
      tags: '@online @convert @verbs @convert-pdf @smoke @live',
    },
    {
      tcid: '12',
      name: '@online-ocr-pdf-smoke',
      path: '/acrobat/online/ocr-pdf',
      verb: 'ocr-pdf',
      data: {},
      tags: '@online @convert @verbs @ocr-pdf @smoke @live',
    },
  ],
};
